apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    - image: zeppelin-server
      context: .
      docker:
        dockerfile: ./.staroid/docker/zeppelin/Dockerfile
    - image: zeppelin-interpreter
      context: .
      docker:
        dockerfile: ./.staroid/docker/interpreter/Dockerfile
  local:
    concurrency: 2
deploy:
  kubectl:
    manifests:
      - .staroid/k8s/zeppelin-conf.yaml
      - .staroid/k8s/zeppelin-server.yaml
      - .staroid/k8s/data-volume.yaml
      - .staroid/k8s/postgres.yaml
      - .staroid/k8s/spark-conf.yaml
profiles:
  - name: prebuilt
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: ./.staroid/docker/zeppelin/Dockerfile_prebuilt
      - op: replace
        path: /build/artifacts/1/docker/dockerfile
        value: ./.staroid/docker/interpreter/Dockerfile_prebuilt
    portForward:
      - resourceType: Service
        resourceName: zeppelin-server
        port: 8080
      - resourceType: Service
        resourceName: file-manager
        port: 8000
  - name: minikube
    deploy:
      kubectl:
        manifests:
          - .staroid/k8s/minikube.yaml
          - .staroid/k8s/zeppelin-conf.yaml
          - .staroid/k8s/zeppelin-server.yaml
          - .staroid/k8s/data-volume.yaml
          - .staroid/k8s/postgres.yaml
          - .staroid/k8s/spark-conf.yaml
  