kind: Pod
apiVersion: v1
metadata:
  namespace: {{zeppelin.k8s.namespace}}
  name: {{zeppelin.k8s.interpreter.pod.name}}
  labels:
    app: {{zeppelin.k8s.interpreter.pod.name}}
    interpreterGroupId: {{zeppelin.k8s.interpreter.group.id}}
    interpreterSettingName: {{zeppelin.k8s.interpreter.setting.name}}
  {% if zeppelin.k8s.server.uid is defined %}
  ownerReferences:
  - apiVersion: v1
    controller: false
    blockOwnerDeletion: false
    kind: Pod
    name: {{zeppelin.k8s.server.pod.name}}
    uid: {{zeppelin.k8s.server.uid}}
  {% endif %}
spec:
  automountServiceAccountToken: true
  restartPolicy: Never
  terminationGracePeriodSeconds: 30
  securityContext:
    runAsUser: 2100
    runAsGroup: 2100
  containers:
  - name: {{zeppelin.k8s.interpreter.container.name}}
    image: {{zeppelin.k8s.interpreter.container.image}}
    command: ["sh", "-c", "$(ZEPPELIN_HOME)/bin/interpreter.sh -d $(ZEPPELIN_HOME)/interpreter/{{zeppelin.k8s.interpreter.group.name}} -r {{zeppelin.k8s.interpreter.rpc.portRange}} -c {{zeppelin.k8s.server.rpc.service}} -p {{zeppelin.k8s.server.rpc.portRange}} -i {{zeppelin.k8s.interpreter.group.id}} -l {{zeppelin.k8s.interpreter.localRepo}} -g {{zeppelin.k8s.interpreter.setting.name}}"]
    lifecycle:
      preStop:
        exec:
          # SIGTERM triggers a quick exit; gracefully terminate instead
          command: ["sh", "-c", "ps -ef | grep org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer | grep -v grep | awk '{print $2}' | xargs kill"]
    env:
  {% for key, value in zeppelin.k8s.envs.items() %}
    - name: {{key}}
      value: {{value}}
  {% endfor %}
  {% if zeppelin.k8s.interpreter.cores is defined and zeppelin.k8s.interpreter.memory is defined %}
    resources:
      requests:
        memory: "{{zeppelin.k8s.interpreter.memory}}"
        cpu: "{{zeppelin.k8s.interpreter.cores}}"
    {# without limits.memory, will see error 'must be less than or equal to memory limit' #}
      limits:
        memory: "{{zeppelin.k8s.interpreter.memory}}"
        cpu: "{{zeppelin.k8s.interpreter.cores}}"
  {% else %}
    resources:
      requests:
        cpu: "1000m"
        memory: "1000Mi"
      limits:
        cpu: "1000m"
        memory: "1000Mi"
  {% endif %}
  {% if zeppelin.k8s.interpreter.group.name == "spark" %}
    volumeMounts:
    - name: spark-home
      mountPath: /spark
  initContainers:
  - name: spark-home-init
    image: {{zeppelin.k8s.spark.container.image}}
    command: ["sh", "-c", "cp -r /opt/spark/* /spark/"]
    volumeMounts:
    - name: spark-home
      mountPath: /spark
    resources:
      requests:
        cpu: "1000m"
        memory: "1000Mi"
      limits:
        cpu: "1000m"
        memory: "1000Mi"
  volumes:
  - name: spark-home
    emptyDir: {}
  {% endif %}
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{zeppelin.k8s.namespace}}
  name: {{zeppelin.k8s.interpreter.pod.name}}             # keep Service name the same to Pod name.
  {% if zeppelin.k8s.server.uid is defined %}
  ownerReferences:
  - apiVersion: v1
    controller: false
    blockOwnerDeletion: false
    kind: Pod
    name: {{zeppelin.k8s.server.pod.name}}
    uid: {{zeppelin.k8s.server.uid}}
  {% endif %}
spec:
  clusterIP: None
  ports:
    - name: intp
      port: 12321
    {% if zeppelin.k8s.interpreter.group.name == "spark" %}
    - name: spark-driver
      port: 22321
    - name: spark-blockmanager
      port: 22322
    - name: spark-ui
      port: 4040
    {% endif %}
  selector:
    app: {{zeppelin.k8s.interpreter.pod.name}}
