kind: ConfigMap
apiVersion: v1
metadata:
  name: spark-conf
data:
  spark-defaults.conf: spark.sql.catalogImplementation                       hive
  generate-spark-defaults.sh: |
    #!/bin/bash

    mkdir -p /spark/conf
    SPARK_DEFAULTS_CONF=/spark/conf/spark-defaults.conf

    # initialize from configmap
    cp /spark-conf/spark-defaults.conf $SPARK_DEFAULTS_CONF

    # generate hive metastore connection info
    echo $HIVE_METASTORE_NAMESPACE | grep not-imported > /dev/null
    if [ $? -ne 0 ]; then
      # add a newline
      echo "" >> $SPARK_DEFAULTS_CONF
      # add generated metastore uri
      cat <<EOT >> $SPARK_DEFAULTS_CONF
    spark.hadoop.hive.metastore.uris  thrift://$HIVE_METASTORE_SERVICE.$HIVE_METASTORE_NAMESPACE:9083
    EOT
    fi
  image: opendatastudio/spark:v3.1.0-snapshot-20200607-02
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: spark-pod-template
data:
  executor-pod-template.yaml: |
    apiVersion: v1
    Kind: Pod
    metadata:
      labels:
        template-label-key: executor-template-label-value
    spec:
      containers:
        - name: executor-container
          image: will-be-overwritten
